server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7j3p79f9bms738grcm0-a:5432/shopdb_9n3y
spring.datasource.username=shopuser
spring.datasource.password=KtjfVdtTe8Ul8sZgkcvqusmclAjSPXB0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
